Revert "Build docs on PRs"
This reverts commit 68ff531c978d39d9c1b38ea7b69a33ea18e5df16.

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -1,4 +1,4 @@
-name: Publish documentation
+name: Documentation
 
 on:
   push:
@@ -8,14 +8,14 @@ on:
 jobs:
   build:
 
-    runs-on: ubuntu-latest
+    runs-on: windows-latest
 
     steps:
     - uses: actions/checkout@v2
-    - name: Set up Python 3.11
+    - name: Set up Python 3.8
       uses: actions/setup-python@v2
       with:
-        python-version: 3.11
+        python-version: 3.8
         
     - name: Install modelskill
       run: |
@@ -26,8 +26,22 @@ jobs:
         cd docs
         make html
     
-    - name: Deploy
-      uses: peaceiris/actions-gh-pages@v3
+    - name: Commit documentation changes
+      run: |
+        git clone https://github.com/DHI/modelskill.git --branch gh-pages --single-branch gh-pages
+        xcopy docs\_build\html gh-pages\ /sy
+        cd gh-pages
+        touch .nojekyll
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update documentation" -a || true
+        # The above command will fail if no changes were present, so we ignore
+        # that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
       with:
+        branch: gh-pages
+        directory: gh-pages
         github_token: ${{ secrets.GITHUB_TOKEN }}
-        publish_dir: ./docs/_build/html
+    # ===============================
